name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test bot imports and basic functionality
      run: |
        python -c "import launch_bot; print('✅ launch_bot imports successfully')"
        python launch_bot.py --test || echo "⚠️ Test mode requires API keys"
    
    - name: Check configuration files
      run: |
        test -f .env.example && echo "✅ .env.example exists"
        test -f requirements.txt && echo "✅ requirements.txt exists"
        test -f README.md && echo "✅ README.md exists"
        test -f FEATURES.md && echo "✅ FEATURES.md exists"
        test -f API.md && echo "✅ API.md exists"
        test -f DEPLOY.md && echo "✅ DEPLOY.md exists"
